image: katalonstudio/katalon
services:
  - docker:dind

job 1:
  script:
    - katalon-execute.sh -browserType="Chrome" -retry=0 -statusDelay=15 -testSuitePath="Test Suites/IP-001( Login )"
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
     - report/
     
job 2:
   script: 
    - katalon-execute.sh -browserType="Chrome" -retry=0 -statusDelay=15 -testSuitePath="Test Suites/IP-002 ( forgot email )"
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
     - report/