image: katalonstudio/katalon
services:
  - docker:dind

stages:
  - Login
  - forgetemail
  - createresident

Login:
  stage: Login
  script:
    - katalon-execute.sh -browserType="Chrome" -retry=0 -statusDelay=15 -testSuitePath="Test Suites/IP-001( Login )"
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
     - report/

forgetemail:
  stage: forgetemail
  script:
    - katalon-execute.sh -browserType="Chrome" -retry=0 -statusDelay=15 -testSuitePath="Test Suites/IP-002 (Forgot Pin)"
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
     - report/

createresident:
  stage: forgetemail
  script:
    - katalon-execute.sh -browserType="Chrome" -retry=0 -statusDelay=15 -testSuitePath="IP-006 ( create resident)"
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
     - report/
          
