image: katalonstudio/katalon
services:
  - docker:dind

stages:
  - test
  - test2
test_job:
  stage: test
  stage: test2
  
  script:
    - katalon-execute.sh -browserType="Chrome" -retry=0 -statusDelay=15 -testSuitePath="Test Suites/IP-001( Login )"
    
  script2:
    - katalon-execute.sh -browserType="Chrome" -retry=0 -statusDelay=15 -testSuitePath="Test Suites/IP-002( forgot email )"    
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
     - report/