version: 2
jobs:
    build:
  
    steps:
      - checkout
      - run:
          name: Execute Katalon Studio
          command: katalon-execute.sh -retry=0 -testSuitePath="Test Suites/IP-001( Login )" -executionProfile="default" -browserType="Chrome (headless)"
      - store-test_results:
          path: ./report
      - store-artifacts:
          path: ./report
   schedules:
  - cron: '*/3 * * * *'
    displayName: Run build each 3min
    branches:
      include:
      - dev
    always: 'true'
  test:
    docker:
      - image: katalonstudio/katalon
