version: 2
jobs:
    build:
   test:
    docker:
      - image: katalonstudio/katalon
    steps:
      - checkout
      - run:
          name: Execute Katalon Studio
          command: katalon-execute.sh -retry=0 -testSuitePath="Test Suites/IP-001( Login )" -executionProfile="default" -browserType="Chrome (headless)"
      - store-test_results:
          path: ./report
      - store-artifacts:
          path: ./report
  jobs:
  build:
  workflows:
  version: 2
  commit:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "*/3 * * * *"
          filters:
            branches:
              only:
                - master
                - beta
    jobs:
      - coverage
      always: 'true'


 
