<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Reset Password</name>
   <tag></tag>
   <elementGuidId>eb5f5b7f-4dc3-4677-a0b7-0ac493175f7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id=':nx']/div/table/tbody/tr/td/table/tbody/tr[2]/td/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr/td/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://u9639404.ct.sendgrid.net/wf/click?upn=nu-2FgXwxQ1qajrlcRaD0Ldfy1U8esigHGro1e9OVaKbWOi8ifWrHNuHi2xTZr4ZvzG-2BHvF2ZcZlYznfbVU0T1rnOL-2BrbSPAddsyDO9RHfrMDOgJ75s3AuFuF5BT90pqbjxw8rIPQQAQjA5jmhgvz39w1l3CGtwYVCNgChqsPRJ4uaEKCO1iUC4tiUn9f9jkeSGlrrU-2BdYkVwsxKyYaB6ZEdyq-2BvJotY-2BdJjB3r2aQY2AwivXqOmUitqX8kK9T2R6HzTJ-2BiMZF3bDOWb-2BV7z26iM6AoPBAIt3wXzhq2-2FVS-2BmHE3H7U-2BOH6aBLxwxna02r-2BpaKgc8J7PI5gc1r0IUb2-2BBKRWl7WdBpJoBN0b0eUaDQjVTtbwkdYZYyE0hyecXlaHgOjB38BwXrsVFOTyQc6ffamVE6-2BbfjvYChw7uG0id0QQCZFYREvchvy71reUFvAJp1CQXfeZi0B64HTjjbrThg8C8NItCTqyrooSwdTSZ-2BjbeakTMXTn5rujqjxp0DcdOCZCWz0BIDkLUPs5vTGVfpRhbCNjTZhceHDgUekq04kA5G9Y-2FDwbBixmDNLRQDk7y06nlHD90TzIkowquoRFMtIQKQHfkxKBjko9hRoAz7dQrgXOR-2BeaZ0j-2Ff93uX-2F-2FtZZ5zNoWpegcFsk6mlM1HsNgUUTfOcldBaLjJqie0uylcbhQeyPdJxOUeKUGgami_FFzaGqYimjb1f6NWZUNJo7zdff0AQcx9IZK0FmTBw5RRR-2B41s87A4oVg0SrQ66eYXTbWttCkfVIBSQHgEtK-2F8hM6X2dt2wy-2BH9jaJ-2FCfS5mAJOjeOT1SMTDpoqprrGJ6BqfGSE7-2BMGA0ZO8M-2BrC4uZwgzfYVrZQX3y4SMuk1PSlMHRVu37SgSE09pAskM7N6a-2FC2wrftd6AJJneQwCbLRqtadECQjdldO1GMkbEddhI-3D</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m_4064006954598829930button m_4064006954598829930button-primary</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-saferedirecturl</name>
      <type>Main</type>
      <value>https://www.google.com/url?q=https://u9639404.ct.sendgrid.net/wf/click?upn%3Dnu-2FgXwxQ1qajrlcRaD0Ldfy1U8esigHGro1e9OVaKbWOi8ifWrHNuHi2xTZr4ZvzG-2BHvF2ZcZlYznfbVU0T1rnOL-2BrbSPAddsyDO9RHfrMDOgJ75s3AuFuF5BT90pqbjxw8rIPQQAQjA5jmhgvz39w1l3CGtwYVCNgChqsPRJ4uaEKCO1iUC4tiUn9f9jkeSGlrrU-2BdYkVwsxKyYaB6ZEdyq-2BvJotY-2BdJjB3r2aQY2AwivXqOmUitqX8kK9T2R6HzTJ-2BiMZF3bDOWb-2BV7z26iM6AoPBAIt3wXzhq2-2FVS-2BmHE3H7U-2BOH6aBLxwxna02r-2BpaKgc8J7PI5gc1r0IUb2-2BBKRWl7WdBpJoBN0b0eUaDQjVTtbwkdYZYyE0hyecXlaHgOjB38BwXrsVFOTyQc6ffamVE6-2BbfjvYChw7uG0id0QQCZFYREvchvy71reUFvAJp1CQXfeZi0B64HTjjbrThg8C8NItCTqyrooSwdTSZ-2BjbeakTMXTn5rujqjxp0DcdOCZCWz0BIDkLUPs5vTGVfpRhbCNjTZhceHDgUekq04kA5G9Y-2FDwbBixmDNLRQDk7y06nlHD90TzIkowquoRFMtIQKQHfkxKBjko9hRoAz7dQrgXOR-2BeaZ0j-2Ff93uX-2F-2FtZZ5zNoWpegcFsk6mlM1HsNgUUTfOcldBaLjJqie0uylcbhQeyPdJxOUeKUGgami_FFzaGqYimjb1f6NWZUNJo7zdff0AQcx9IZK0FmTBw5RRR-2B41s87A4oVg0SrQ66eYXTbWttCkfVIBSQHgEtK-2F8hM6X2dt2wy-2BH9jaJ-2FCfS5mAJOjeOT1SMTDpoqprrGJ6BqfGSE7-2BMGA0ZO8M-2BrC4uZwgzfYVrZQX3y4SMuk1PSlMHRVu37SgSE09pAskM7N6a-2FC2wrftd6AJJneQwCbLRqtadECQjdldO1GMkbEddhI-3D&amp;source=gmail&amp;ust=1568173153124000&amp;usg=AFQjCNF5GfO5UBVYqvnUJrryR-flZn3ZSA</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Reset Password</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:nb&quot;)/div[1]/table[@class=&quot;m_4064006954598829930wrapper&quot;]/tbody[1]/tr[1]/td[1]/table[@class=&quot;m_4064006954598829930content&quot;]/tbody[1]/tr[2]/td[@class=&quot;m_4064006954598829930body&quot;]/table[@class=&quot;m_4064006954598829930inner-body&quot;]/tbody[1]/tr[1]/td[@class=&quot;m_4064006954598829930content-cell&quot;]/table[@class=&quot;m_4064006954598829930action&quot;]/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[1]/td[1]/a[@class=&quot;m_4064006954598829930button m_4064006954598829930button-primary&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id=':nb']/div/table/tbody/tr/td/table/tbody/tr[2]/td/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr/td/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Reset Password')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Need Your Attention,'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='iProp.io'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='feedback@iprop.io'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://u9639404.ct.sendgrid.net/wf/click?upn=nu-2FgXwxQ1qajrlcRaD0Ldfy1U8esigHGro1e9OVaKbWOi8ifWrHNuHi2xTZr4ZvzG-2BHvF2ZcZlYznfbVU0T1rnOL-2BrbSPAddsyDO9RHfrMDOgJ75s3AuFuF5BT90pqbjxw8rIPQQAQjA5jmhgvz39w1l3CGtwYVCNgChqsPRJ4uaEKCO1iUC4tiUn9f9jkeSGlrrU-2BdYkVwsxKyYaB6ZEdyq-2BvJotY-2BdJjB3r2aQY2AwivXqOmUitqX8kK9T2R6HzTJ-2BiMZF3bDOWb-2BV7z26iM6AoPBAIt3wXzhq2-2FVS-2BmHE3H7U-2BOH6aBLxwxna02r-2BpaKgc8J7PI5gc1r0IUb2-2BBKRWl7WdBpJoBN0b0eUaDQjVTtbwkdYZYyE0hyecXlaHgOjB38BwXrsVFOTyQc6ffamVE6-2BbfjvYChw7uG0id0QQCZFYREvchvy71reUFvAJp1CQXfeZi0B64HTjjbrThg8C8NItCTqyrooSwdTSZ-2BjbeakTMXTn5rujqjxp0DcdOCZCWz0BIDkLUPs5vTGVfpRhbCNjTZhceHDgUekq04kA5G9Y-2FDwbBixmDNLRQDk7y06nlHD90TzIkowquoRFMtIQKQHfkxKBjko9hRoAz7dQrgXOR-2BeaZ0j-2Ff93uX-2F-2FtZZ5zNoWpegcFsk6mlM1HsNgUUTfOcldBaLjJqie0uylcbhQeyPdJxOUeKUGgami_FFzaGqYimjb1f6NWZUNJo7zdff0AQcx9IZK0FmTBw5RRR-2B41s87A4oVg0SrQ66eYXTbWttCkfVIBSQHgEtK-2F8hM6X2dt2wy-2BH9jaJ-2FCfS5mAJOjeOT1SMTDpoqprrGJ6BqfGSE7-2BMGA0ZO8M-2BrC4uZwgzfYVrZQX3y4SMuk1PSlMHRVu37SgSE09pAskM7N6a-2FC2wrftd6AJJneQwCbLRqtadECQjdldO1GMkbEddhI-3D')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/table/tbody/tr/td/table/tbody/tr/td/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id=':mw']/div/table/tbody/tr/td/table/tbody/tr[2]/td/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr/td/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://u9639404.ct.sendgrid.net/wf/click?upn=nu-2FgXwxQ1qajrlcRaD0Ldfy1U8esigHGro1e9OVaKbWOi8ifWrHNuHi2xTZr4ZvzG-2BHvF2ZcZlYznfbVU0T1rnOL-2BrbSPAddsyDO9RHfrMDOgJ75s3AuFuF5BT90pqbjxw8rIPQQAQjA5jmhgvz39w1l3CGtwYVCNgChqsPRJ4uaEKCO1iUC4tiUn9f9jkeSGlrrU-2BdYkVwsxKyYaB6ZEdyq-2BvJotY-2BdJjB3r2aQY2AwivXqOmUitqX8kK9T2R6H0tchXZd-2FNHhFnJMTcHHBHE8z-2FVOHPuwJA7qES-2FezJRgCRVrv51iaPa4J1tMuoOhdXlvpA7OOOi-2Bh57s0tcyTkBgf2MWb9-2B-2FeQ0eW86fonP-2FVOFw4c4-2BtVv6bPHaYhO0AuzSl6Ph7k96LP2fb6ULorOzEU4nzGwzIAtv6YpK2UaCg36f8mukEuzl2Ms-2F6JLsUnSXbem2nBdMf-2BBwrrhXP-2BPY6gO8dgLr49xuToOPjezsu2XZQyZ6FU986peHige7SE1zi50Kj1otLSXWWeZkbotgHiYPNHmIKAE3-2FG2HX2WyA3FwqedlCjFKWZ4AOEv89Se-2BeyPt95wafyR3u-2FzmNY-2Fv9cAJ9rzw7VW8N4NvVQ-2FYMbdC70aVpzoIbiAvk0tlNpsYtHYNXHWcfUY0scOWAsNWUlhIkEgYz0o6XreCoApxQM2CjbGFTTTKUvZg9Rr0n_FFzaGqYimjb1f6NWZUNJo7zdff0AQcx9IZK0FmTBw5Q66-2F8nDX2TQCgGmuDhvtRHDoUCkREe0lSQu4WpHcxQwHV-2BgbCGO0bWosLfkreMf8bG0fjcKAGC5DlbqmnlWe4eSfvH6Goip-2BibwR-2BYEsKtI5cY-2Bmbir1D79K9ppUEkr1U5BC8SVnZa-2FPQKoNyEadpNtQvlBS1YOgy5BBKmv3LhJGeywgX-2FR-2FSwh7fJY06ieck-3D')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id=':nx']/div/table/tbody/tr/td/table/tbody/tr[2]/td/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr/td/a</value>
   </webElementXpaths>
</WebElementEntity>
